name: Testing - main

on: [push, pull_request]


jobs:
  test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [
          "ubuntu-latest",
          #"macos-latest",
          # "windows-latest"
        ]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge rdkit openbabel==3.1.1
          conda install -c conda-forge tqdm
          conda install -c conda-forge tabulate
          #git clone https://github.com/polysimtools/pysimm
          #sudo python pysimm/complete_install.py --pysimm $PWD
          #source ~/.bashrc
          python -m pip install --upgrade pip
          pip install networkx
          pip install -e .
      - name: pytest
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          pytest test/test.py --color=yes --cov=psp --cov-report html:coverage_reports
